cursor #181c1f
cursor_text_color #41484d

foreground            #181c1f
background            #f6fafe
selection_foreground  #ffffff
selection_background  #b6c9d8
url_color             #206487

color0   #0f1417
color1   #8c0b0e
color2   #0d7209
color3   #7f7111
color4   #54cbff
color5   #3e96d0
color6   #92cef5
color7   #1a1a1a
color8   #2e2e2e
color9   #a52023
color10  #188c13
color11  #998a21
color12  #8dd2ff
color13  #3fd6ff
color14  #596eff
color15  #1a1a1a